<?php
/**
 * Exam syllabi: structured subject → subtopics data for supported exams.
 * Used by the AI question generator to show relevant topic suggestions
 * based on the selected exam type, and to auto-fill subjects for section tabs.
 *
 * Format: 'Exam Name' => [ 'Subject (section tab)' => ['Topic 1', 'Topic 2', ...], ... ]
 *
 * ONLY the top-level numbered sections become subject/section tabs.
 * Subtopics are shown as topic suggestions in the AI generator.
 */

if (!defined('ROOT')) die('Direct access not allowed');

$EXAM_SYLLABI = [

    'UP Police' => [
        'General Knowledge' => [
            'Indian History - Ancient',
            'Indian History - Medieval',
            'Indian History - Modern',
            'Freedom Struggle & Important Movements',
            'Important Personalities',
            'Indian Polity & Constitution',
            'Preamble & Fundamental Rights',
            'Fundamental Duties & Directive Principles',
            'Parliament, President & Prime Minister',
            'Supreme Court & High Courts',
            'Constitutional Amendments',
            'Physical Geography',
            'Indian Geography',
            'World Geography',
            'Rivers, Mountains & Climate',
            'Natural Resources, Soil & Agriculture',
            'Indian Economy & Banking',
            'Budget & Five-Year Plans',
            'GDP, Inflation & Tax System',
            'Government Schemes',
            'Physics',
            'Chemistry',
            'Biology & Human Body',
            'Scientific Instruments',
            'Inventions & Discoveries',
            'Current Affairs - National',
            'Current Affairs - International',
            'Current Affairs - Sports',
            'Awards & Important Days',
            'Appointments',
            'History of UP',
            'Geography of UP',
            'Rivers of UP',
            'Economy of UP',
            'Culture & Festivals of UP',
            'UP Government Schemes',
            'Sports',
            'Books & Authors',
            'Awards & Honors',
            'Important Organizations',
            'International Organizations',
            'Cyber Crime',
            'Human Rights',
            'Environment & Technology',
        ],
        'General Hindi' => [
            'संज्ञा',
            'सर्वनाम',
            'विशेषण',
            'क्रिया',
            'अव्यय',
            'काल',
            'वचन',
            'लिंग',
            'कारक',
            'समास',
            'संधि',
            'पर्यायवाची शब्द',
            'विलोम शब्द',
            'अनेकार्थी शब्द',
            'तत्सम-तद्भव',
            'देशज शब्द',
            'विदेशी शब्द',
            'वाक्य शुद्धि',
            'अशुद्धि सुधार',
            'वाक्यांश के लिए एक शब्द',
            'मुहावरे',
            'लोकोक्तियाँ',
            'अपठित गद्यांश',
        ],
        'Numerical & Mental Ability' => [
            'Number System',
            'Simplification',
            'Decimal & Fraction',
            'HCF & LCM',
            'Percentage',
            'Ratio & Proportion',
            'Partnership',
            'Average',
            'Profit & Loss',
            'Discount',
            'Simple Interest',
            'Compound Interest',
            'Time & Work',
            'Pipes & Cistern',
            'Time Speed & Distance',
            'Boat & Stream',
            'Mensuration',
            'Data Interpretation',
            'Tabulation',
            'Graph Analysis',
            'Arithmetic Reasoning',
        ],
        'Mental Aptitude / Reasoning' => [
            'Analogy',
            'Classification',
            'Series',
            'Coding-Decoding',
            'Alphabet Test',
            'Ranking Test',
            'Direction Test',
            'Blood Relation',
            'Statement & Conclusion',
            'Cause & Effect',
            'Syllogism',
            'Assumption',
            'Decision Making',
            'Mirror Image',
            'Water Image',
            'Paper Folding',
            'Embedded Figure',
            'Figure Completion',
            'Puzzle',
            'Seating Arrangement',
            'Venn Diagram',
            'Logical Sequence',
            'Data Sufficiency',
            'Public Interest',
            'Law & Order',
            'Crime Control',
            'Problem Solving',
            'Social Responsibility',
            'Police System Awareness',
        ],
    ],

    'SSC' => [
        'General Awareness' => [
            'Indian History',
            'Indian Polity',
            'Geography',
            'Indian Economy',
            'General Science',
            'Current Affairs',
            'Static GK',
        ],
        'Quantitative Aptitude' => [
            'Number System',
            'Percentage',
            'Ratio & Proportion',
            'Average',
            'Profit & Loss',
            'SI & CI',
            'Time & Work',
            'Time Speed Distance',
            'Geometry',
            'Mensuration',
            'Trigonometry',
            'Algebra',
            'Data Interpretation',
        ],
        'English' => [
            'Reading Comprehension',
            'Cloze Test',
            'Error Spotting',
            'Sentence Improvement',
            'Synonyms & Antonyms',
            'Idioms & Phrases',
            'One Word Substitution',
            'Active Passive Voice',
            'Direct Indirect Speech',
        ],
        'Reasoning' => [
            'Analogy',
            'Classification',
            'Series',
            'Coding-Decoding',
            'Direction & Distance',
            'Blood Relation',
            'Syllogism',
            'Mirror & Water Image',
            'Paper Folding',
            'Puzzle',
            'Seating Arrangement',
            'Venn Diagram',
        ],
    ],

    'Railway' => [
        'General Awareness' => [
            'Indian History',
            'Indian Polity',
            'Geography',
            'General Science',
            'Current Affairs',
            'Indian Railway GK',
        ],
        'Mathematics' => [
            'Number System',
            'Percentage',
            'Ratio & Proportion',
            'Profit & Loss',
            'SI & CI',
            'Time & Work',
            'Time Speed Distance',
            'Mensuration',
            'Algebra',
            'Geometry',
        ],
        'Reasoning' => [
            'Analogy',
            'Classification',
            'Series',
            'Coding-Decoding',
            'Direction Test',
            'Blood Relation',
            'Syllogism',
            'Non-Verbal Reasoning',
        ],
        'General Science' => [
            'Physics',
            'Chemistry',
            'Biology',
            'Human Body',
            'Inventions & Discoveries',
        ],
    ],

    'Banking' => [
        'Reasoning Ability' => [
            'Syllogism',
            'Coding-Decoding',
            'Inequality',
            'Seating Arrangement',
            'Puzzle',
            'Blood Relation',
            'Direction',
            'Input-Output',
            'Data Sufficiency',
        ],
        'Quantitative Aptitude' => [
            'Number Series',
            'Simplification',
            'Percentage',
            'Ratio & Proportion',
            'Profit & Loss',
            'SI & CI',
            'Time & Work',
            'Data Interpretation',
            'Quadratic Equation',
        ],
        'English' => [
            'Reading Comprehension',
            'Cloze Test',
            'Error Spotting',
            'Sentence Rearrangement',
            'Fill in the Blanks',
            'Vocabulary',
        ],
        'General Awareness' => [
            'Banking Awareness',
            'Financial Awareness',
            'Current Affairs',
            'Static GK',
            'Economy',
        ],
    ],

    'UPSC' => [
        'General Studies I' => [
            'Indian History & Culture',
            'World History',
            'Indian Geography',
            'World Geography',
            'Indian Society',
        ],
        'General Studies II' => [
            'Indian Polity & Governance',
            'International Relations',
            'Social Justice',
        ],
        'General Studies III' => [
            'Indian Economy',
            'Science & Technology',
            'Environment & Ecology',
            'Disaster Management',
            'Internal Security',
        ],
        'General Studies IV' => [
            'Ethics & Integrity',
            'Aptitude',
            'Case Studies',
        ],
    ],

    'Defence' => [
        'General Knowledge' => [
            'Indian History',
            'Geography',
            'Indian Polity',
            'Economy',
            'General Science',
            'Current Affairs',
            'Defence & Security',
        ],
        'Mathematics' => [
            'Algebra',
            'Arithmetic',
            'Trigonometry',
            'Geometry',
            'Mensuration',
            'Statistics',
        ],
        'English' => [
            'Grammar',
            'Vocabulary',
            'Comprehension',
            'Sentence Correction',
        ],
        'Reasoning' => [
            'Verbal Reasoning',
            'Non-Verbal Reasoning',
            'Spatial Reasoning',
        ],
    ],

];
